"""
Fetch a YouTube transcript and save it as src/data/transcript.json.

Run it with:   python ingest.py

Runs locally on purpose -- see DECISIONS.md. YouTube blocks these endpoints
from datacenter IPs, which is where this project deploys. So ingestion happens
here, on a real machine, and the JSON it produces gets committed to the repo.

To use it: edit the settings below, run it, commit the JSON.
"""

import json
import os

from youtube_transcript_api import YouTubeTranscriptApi


# ---- settings -------------------------------------------------------------

VIDEO_ID = "j3Pq35gm4qA"
TITLE = "NASA’s Artemis II Daily News Conference (April 2, 2026) "
LICENSE = "Public domain - NASA"

OUTPUT_FOLDER = "src/data"
OUTPUT_FILE = "src/data/transcript.json"

# A chunk gets cut off at this many seconds even mid-sentence, so one
# rambling answer can't become a 90-second wall of text.
MAX_CHUNK_SECONDS = 12

SENTENCE_ENDINGS = (".", "?", "!")


# ---- fetch ----------------------------------------------------------------

api = YouTubeTranscriptApi()
fetched = api.fetch(VIDEO_ID)


# ---- reshape --------------------------------------------------------------
# Caption files break speech into 3-6 word DISPLAY lines, chopped wherever the
# text hit the edge of the screen. Straight out of the API you get things like:
#
#     {'start': 15.02, 'text': '>> Good evening, and welcome to'}
#     {'start': 16.45, 'text': "NASA's Johnson Space Center in"}
#
# That is unusable for search. A phrase can straddle two lines and match
# neither of them, and a single line shown as a search result reads like
# "this briefing. I would".
#
# So we glue consecutive lines back into sentence-sized chunks. A chunk ends
# when its text reaches a sentence-ending mark, or when it has been running
# longer than MAX_CHUNK_SECONDS. Broadcast captions write ">>" at a speaker
# change, so that always starts a fresh chunk too.
#
# The chunk keeps the START time of its FIRST line -- clicking a search result
# should drop you at the beginning of the sentence, not the middle.


def make_chunk(start, words):
    return {"start": round(start, 2), "text": " ".join(words)}


segments = []

chunk_start = None
chunk_words = []

for snippet in fetched.snippets:
    text = snippet.text.strip()

    if text == "":
        continue

    new_speaker = text.startswith(">>")
    if new_speaker:
        text = text.lstrip(">").strip()
        if text == "":
            continue

    running_too_long = (
        chunk_start is not None
        and snippet.start - chunk_start > MAX_CHUNK_SECONDS
    )

    # Close out the chunk in progress before starting a new one.
    if chunk_words and (new_speaker or running_too_long):
        segments.append(make_chunk(chunk_start, chunk_words))
        chunk_words = []
        chunk_start = None

    if chunk_start is None:
        chunk_start = snippet.start

    chunk_words.append(text)

    # A finished sentence is the natural place to stop.
    if text.endswith(SENTENCE_ENDINGS):
        segments.append(make_chunk(chunk_start, chunk_words))
        chunk_words = []
        chunk_start = None

# Whatever was still being built when the transcript ran out.
if chunk_words:
    segments.append(make_chunk(chunk_start, chunk_words))


# ---- assemble -------------------------------------------------------------

data = {
    "videoId": VIDEO_ID,
    "title": TITLE,
    "source": "https://www.youtube.com/watch?v=" + VIDEO_ID,
    "license": LICENSE,
    "language": fetched.language_code,
    "autoGenerated": fetched.is_generated,
    "segments": segments,
}


# ---- write ----------------------------------------------------------------

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

with open(OUTPUT_FILE, "w", encoding="utf-8") as output_file:
    json.dump(data, output_file, indent=2, ensure_ascii=False)

print("wrote " + str(len(segments)) + " chunks to " + OUTPUT_FILE)
