"""
Fetch a YouTube transcript and save it as src/data/transcript.json.

Run it with:   python ingest.py

Runs locally on purpose -- see DECISIONS.md. YouTube blocks these endpoints
from datacenter IPs, which is where this project deploys. So ingestion happens
here, on a real machine, and the JSON it produces gets committed to the repo.

To use it: edit the three settings below, run it, commit the JSON.
"""

import json
import os

from youtube_transcript_api import YouTubeTranscriptApi


# ---- settings -------------------------------------------------------------

VIDEO_ID = "j3Pq35gm4qA"
TITLE = "NASA’s Artemis II Daily News Conference (April 2, 2026)"
LICENSE = "Public domain - NASA"

OUTPUT_FOLDER = "src/data"
OUTPUT_FILE = "src/data/transcript.json"


# ---- fetch ----------------------------------------------------------------

api = YouTubeTranscriptApi()
fetched = api.fetch(VIDEO_ID)


# ---- reshape --------------------------------------------------------------
# The library gives us objects. We want plain dictionaries, because those are
# what json can write out. One dictionary per caption line.

segments = []

for snippet in fetched.snippets:
    one_line = {
        "start": round(snippet.start, 2),
        "text": snippet.text.strip(),
    }
    segments.append(one_line)


# ---- assemble -------------------------------------------------------------

data = {
    "videoId": VIDEO_ID,
    "title": TITLE,
    "source": "https://www.youtube.com/watch?v=" + VIDEO_ID,
    "license": LICENSE,
    "language": fetched.language_code,
    "autoGenerated": fetched.is_generated,
    "segments": segments,
}


# ---- write ----------------------------------------------------------------

os.makedirs(OUTPUT_FOLDER, exist_ok=True)

with open(OUTPUT_FILE, "w", encoding="utf-8") as output_file:
    json.dump(data, output_file, indent=2, ensure_ascii=False)

print("wrote " + str(len(segments)) + " segments to " + OUTPUT_FILE)
